wire:
  shutdownTimeout: 10s
logger:
  development: true
  format: text # text / json
  level: debug # debug / info / warn / error / panic / fatal
  stackTrace: false
  caller: true
http:
  host: "0.0.0.0"
  port: 18412
