main:
  initTimeout: 30s
  shutdownTimeout: 30s
logger:
  format: text # text / json
  reportCaller: false
  stackTrace: false
server:
  http:
    host: '0.0.0.0'
    port: 8499
postgres:
  host: localhost
  port: 59183
  database: goarch
  user: user
  password: user123
